disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - colon
  - comma

opt_in_rules: # some rules are only opt-in
  - empty_count
  - explicit_init

included: # paths to include during linting. `--path` is ignored if present.
  - Source

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder

line_length: 120

vertical_whitespace:
  max_empty_lines: 1
